name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nose2, flake8, mypy
        pip install .
    - name: Run linters
      run: |
        flake8
        mypy .
    - name: Run tests
      run: |
        nose2 -v
    - name: Build wheel
      run: |
        python setup.py bdist_wheel
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: dist/*.whl